package com.bkhech.boot.sample.mvc.mapper.user;

import com.bkhech.boot.sample.mvc.model.user.UserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.bkhech.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: UserInfoMapper
 * Model : UserInfo
 * Table : tb_userinfo
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-05 19:33:49
 */
@Mapper
public interface UserInfoMapper extends GenericMapper<UserInfo, Integer> {
}