package com.bkhech.boot.sample.mvc.mapper.event;

import com.bkhech.boot.sample.mvc.model.event.EventLog;
import org.apache.ibatis.annotations.Mapper;
import org.bkhech.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: EventLogMapper
 * Model : EventLog
 * Table : sdk_event_log
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-05-08 17:20:46
 */
@Mapper
public interface EventLogMapper extends GenericMapper<EventLog, Integer> {
}