package com.bkhech.boot.sample.mvc.service.user;

import com.bkhech.boot.sample.mvc.model.user.UserInfo;
import org.bkhech.mybatis.extend.generic.service.GenericService;

/**
 * Service: UserInfoService
 * Mapper : UserInfoMapper
 * Model  : UserInfo
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-05 19:33:49
 */
public interface UserInfoService extends GenericService<UserInfo, Integer> {
}