package com.bkhech.boot.sample.mvc.service.user.impl;

import com.bkhech.boot.sample.mvc.mapper.user.UserInfoMapper;
import com.bkhech.boot.sample.mvc.model.user.UserInfo;
import com.bkhech.boot.sample.mvc.service.user.UserInfoService;
import org.bkhech.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * ServiceImpl: UserInfoServiceImpl
 * Mapper : UserInfoMapper
 * Model  : UserInfo
 *
 * This ServiceImpl generated by MyBatis Generator Extend at 2018-12-05 19:33:49
 */
@Service
@Transactional
public class UserInfoServiceImpl extends GenericServiceImpl<UserInfo, Integer, UserInfoMapper> implements UserInfoService {
    @Autowired
    private UserInfoMapper userInfoMapper;

    @Override
    public UserInfoMapper getGenericMapper() {
        return userInfoMapper;
    }
}