spring:
  redis:
    host: 192.168.71.71
    port: 6379
    password: 123456
    database: 1
    timeout: 500
    jedis:
      pool:
        max-idle: 10
        max-active: 10
        max-wait: 500
        min-idle: 0

