package com.bkhech.boot.sample.swagger.model.event;

import java.io.Serializable;

import com.bkhech.boot.commons.annotation.TheadIgnore;
import org.bkhech.mybatis.extend.generic.model.BasePrimaryKeyModel;

/**
 * Model: EventLog
 * Table: sdk_event_log
 * Alias: sel
 *
 * This Model generated by MyBatis Generator Extend.
 */
public class EventLog extends BasePrimaryKeyModel<Integer> implements Serializable {
    /**
     * 
     * ad_id
     */
    private Integer ad_id;

    /**
     * 
     * game_id
     */
    private Integer game_id;

    /**
     * 
     * event
     */
    private String event;

    /**
     * 
     * uid
     */
    @TheadIgnore
    private Integer uid;

    /**
     * 
     * uuid
     */
    private String uuid;

    /**
     * 
     * ip
     */
    private String ip;

    /**
     * 
     * data
     */
    private String data;

    /**
     * 
     * server_datetime
     */
    private Long server_datetime;

    /**
     * 
     * server_date
     */
    private Integer server_date;

    /**
     * 
     * server_hour
     */
    private Integer server_hour;

    private static final long serialVersionUID = 1L;

    /**
     * 
     * ad_id
     */
    public Integer getAd_id() {
        return ad_id;
    }

    /**
     * 
     * ad_id
     *
     * @param ad_id 
     */
    public void setAd_id(Integer ad_id) {
        this.ad_id = ad_id;
    }

    /**
     * 
     * game_id
     */
    public Integer getGame_id() {
        return game_id;
    }

    /**
     * 
     * game_id
     *
     * @param game_id 
     */
    public void setGame_id(Integer game_id) {
        this.game_id = game_id;
    }

    /**
     * 
     * event
     */
    public String getEvent() {
        return event;
    }

    /**
     * 
     * event
     *
     * @param event 
     */
    public void setEvent(String event) {
        this.event = event;
    }

    /**
     * 
     * uid
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 
     * uid
     *
     * @param uid 
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * 
     * uuid
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * 
     * uuid
     *
     * @param uuid 
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * 
     * ip
     */
    public String getIp() {
        return ip;
    }

    /**
     * 
     * ip
     *
     * @param ip 
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * 
     * data
     */
    public String getData() {
        return data;
    }

    /**
     * 
     * data
     *
     * @param data 
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * 
     * server_datetime
     */
    public Long getServer_datetime() {
        return server_datetime;
    }

    /**
     * 
     * server_datetime
     *
     * @param server_datetime 
     */
    public void setServer_datetime(Long server_datetime) {
        this.server_datetime = server_datetime;
    }

    /**
     * 
     * server_date
     */
    public Integer getServer_date() {
        return server_date;
    }

    /**
     * 
     * server_date
     *
     * @param server_date 
     */
    public void setServer_date(Integer server_date) {
        this.server_date = server_date;
    }

    /**
     * 
     * server_hour
     */
    public Integer getServer_hour() {
        return server_hour;
    }

    /**
     * 
     * server_hour
     *
     * @param server_hour 
     */
    public void setServer_hour(Integer server_hour) {
        this.server_hour = server_hour;
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EventLog other = (EventLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" {");
        sb.append("id=").append(getId());
        sb.append(", ad_id=").append(getAd_id());
        sb.append(", game_id=").append(getGame_id());
        sb.append(", event=").append(getEvent());
        sb.append(", uid=").append(getUid());
        sb.append(", uuid=").append(getUuid());
        sb.append(", ip=").append(getIp());
        sb.append(", data=").append(getData());
        sb.append(", server_datetime=").append(getServer_datetime());
        sb.append(", server_date=").append(getServer_date());
        sb.append(", server_hour=").append(getServer_hour());
        sb.append("}");
        return sb.toString();
    }
}