---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guowm.
--- DateTime: 2021/6/28 9:35
---

--获取KEY
local key1 = KEYS[1]
local key2 = KEYS[2]
print("key1" .. key1)
print("key2" .. key2)

-- 获取ARGV[1],这里对应到应用端是一个List<Map>.
--  注意，这里接收到是的字符串，所以需要用csjon库解码成table类型
local receive_arg_json =  cjson.decode(ARGV[1])

--获取ARGV内的参数并打印
local expire = receive_arg_json.expire
local times = receive_arg_json.times

print("expire" .. expire)
print("times" .. times)

-- 获取key
tab1 = {
    key1 = "val1",
    key2 = "val2",
    "val3"
}
for k, v in pairs(tab1) do
    print(k .. " - " ..v)
end

print("---------------")

tab1.key1 = nil
for k, v in pairs(tab1) do
    print(k .. " - " ..v)
end