---
--- 原子删除存在的key，释放锁
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guowm.
--- DateTime: 2021/9/2 15:38
---
--- 如果对应的value等于传入的值
if redis.call('get', KEYS[1]) == ARGV[1] then
    -- 执行删除操作
    return redis.call('del', KEYS[1])
else
    -- 不成功，返回0
    return 0;
end