package com.bkhech.boot.sample.mvc.service.event;

import com.bkhech.boot.sample.mvc.model.event.EventLog;
import org.bkhech.mybatis.extend.generic.service.GenericService;

/**
 * Service: EventLogService
 * Mapper : EventLogMapper
 * Model  : EventLog
 *
 * This Service generated by MyBatis Generator Extend at 2018-05-08 17:20:46
 */
public interface EventLogService extends GenericService<EventLog, Integer> {

    EventLog getById(Integer id);

    EventLog save(EventLog eventLog);

}